create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table session (
    session_id bigint generated by default as identity,
    title varchar(255) not null,
    sale_price bigint not null,
    state_code bigint not null,
    progress_code bigint not null,
    student_max_count bigint not null,
    creator_id varchar(30) not null,
    apply_start_date timestamp not null,
    apply_end_date timestamp not null,
    session_type varchar(30) not null,
    primary key (session_id)
);

create table session_image (
     image_id bigint generated by default as identity,
     session_id bigint not null,
     file_name varchar(255) not null,
     file_size bigint not null,
     type varchar(10) not null,
     width bigint not null,
     height bigint not null,
     primary key (image_id)
     --foreign key (session_id) references session(session_id)
);

--ALTER TABLE session_image DROP CONSTRAINT CONSTRAINT_FB;

create table session_order (
    order_id bigint generated by default as identity,
    session_id bigint not null,
    ns_user_id bigint not null,
    sale_price bigint not null,
    ord_stat_code bigint not null, -- 최종 상태만 나타냄 대기 10 승인 20 취소 30
    appr_id bigint, -- 승인자
    primary key (order_id),
    foreign key (session_id) references session(session_id),
    foreign key (ns_user_id) references ns_user(id),
    unique (session_id,ns_user_id)
);
-- ALTER TABLE session_order ADD COLUMN ord_stat_code BIGINT NOT NULL;

/*
drop table session;

drop table session_image;
drop table session_order;

--drop table ns_user;
 */
